# Generated by Django 5.2.12 on 2026-04-25 13:09

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_taskgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskgroup',
            name='invite_code',
            field=models.CharField(default=tasks.models.generate_invite_code, max_length=12, unique=True),
        ),
    ]
